rvm:
  - 1.9.3
  - 1.9.2
before_install:
  - 'mv config/database.sample.yml config/database.yml'
notifications:
  email:
    - luiz@engage.is
before_script:
  - "psql -c 'create database myapp_test;' -U postgres"
  - "rake db:test:prepare"
